-- This migration was attempting to modify foreign keys for tables that don't exist yet.
-- The lead_notes, lead_emails, and lead_activities tables are created in a later migration.
-- Foreign key constraints for these tables are set correctly when the tables are created.
-- This migration is now empty but kept for migration history consistency.
